### ISSUE TITLE
Update to v0.11.13 please

### ISSUE THREAD

**Issue by fmauch** [ros-noetic-arch/ros-noetic-rosbridge-suite#1]
https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml#L6153

Also see 
 - https://github.com/ros-noetic-arch/ros-noetic-rosbridge-msgs/issues/1
 - https://github.com/ros-noetic-arch/ros-noetic-rosbridge-server/issues/1
 - https://github.com/ros-noetic-arch/ros-noetic-rosbridge-library/issues/1
 - https://github.com/ros-noetic-arch/ros-noetic-rosapi/issues/1

Edit: Sorry for not opening PRs, but I think the efforts of forking, changing and writing PRs stands in no relation to the single script call using [ros-aur-helpers](https://github.com/ros-arch/ros-aur-helpers)

**Comment by acxz** [comment]
Done with 679c47f
